### ISSUE TITLE
Watchword is not working on node v19.3.0 or above.

### ISSUE THREAD

**Issue by ivansantiagojr** [allogaztea/watchword#16]
I tried to use watchword on node 19.3.0 or above and the following error message was displayed:

![image](https://user-images.githubusercontent.com/65205079/215591527-bf95dcda-27fc-42e6-b0f5-46047a97939f.png)

**Comment by allogaztea** [comment]
We coudn't reproduce the bug, but we'll include tests in various versions of NodeJS.
